version: '3.8'

services:
  mysql:
    image: mysql:8.0.33
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: biblioteca_digital
      MYSQL_USER: usuario
      MYSQL_PASSWORD: clave
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - backend_net

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: biblioteca_digital_fer
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:mysql://mysql:3306/biblioteca_digital?useSSL=false&serverTimezone=UTC
      DB_USER: usuario
      DB_PASSWORD: clave
    networks:
      - backend_net

volumes:
  mysql_data:

networks:
  backend_net:
    driver: bridge
